[2024-10-08T21:51:58.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T21:51:58.830+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [queued]>
[2024-10-08T21:51:58.842+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [queued]>
[2024-10-08T21:51:58.842+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-08T21:51:58.857+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_extract_container_E3> on 2024-10-08 21:51:57.135226+00:00
[2024-10-08T21:51:58.866+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T21:51:58.867+0000] {standard_task_runner.py:72} INFO - Started process 1137 to run task
[2024-10-08T21:51:58.868+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_004', 'run_extract_container_E3', 'manual__2024-10-08T21:51:57.135226+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp6sh3ug0y']
[2024-10-08T21:51:58.869+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask run_extract_container_E3
[2024-10-08T21:51:58.917+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [running]> on host a4706156eccf
[2024-10-08T21:51:59.003+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_004' AIRFLOW_CTX_TASK_ID='run_extract_container_E3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T21:51:57.135226+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T21:51:57.135226+00:00'
[2024-10-08T21:51:59.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T21:51:59.029+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-08T21:51:59.033+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-08T21:56:24.019+0000] {docker.py:438} INFO - End of process...
[2024-10-08T21:56:24.020+0000] {docker.py:438} INFO -    Category  ...   Like_First
[2024-10-08T21:56:24.021+0000] {docker.py:438} INFO - 0   Romance  ...   like13,155
[2024-10-08T21:56:24.021+0000] {docker.py:438} INFO - 1   Romance  ...  like140,859
[2024-10-08T21:56:24.021+0000] {docker.py:438} INFO - 2   Romance  ...   like30,213
[2024-10-08T21:56:24.022+0000] {docker.py:438} INFO - 3   Fantasy  ...   like27,534
[2024-10-08T21:56:24.022+0000] {docker.py:438} INFO - 4   Romance  ...   like40,306
[2024-10-08T21:56:24.022+0000] {docker.py:438} INFO - ..      ...  ...          ...
[2024-10-08T21:56:24.022+0000] {docker.py:438} INFO - 68   Horror  ...    like9,598
[2024-10-08T21:56:24.023+0000] {docker.py:438} INFO - 69  Romance  ...   like67,401
[2024-10-08T21:56:24.023+0000] {docker.py:438} INFO - 70    Drama  ...    like4,928
[2024-10-08T21:56:24.023+0000] {docker.py:438} INFO - 71  Fantasy  ...   like88,554
[2024-10-08T21:56:24.023+0000] {docker.py:438} INFO - 72  Fantasy  ...  like136,523
[2024-10-08T21:56:24.023+0000] {docker.py:438} INFO - 
[2024-10-08T21:56:24.024+0000] {docker.py:438} INFO - [73 rows x 9 columns]
[2024-10-08T21:56:24.503+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T21:56:24.504+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_004, task_id=run_extract_container_E3, run_id=manual__2024-10-08T21:51:57.135226+00:00, execution_date=20241008T215157, start_date=20241008T215158, end_date=20241008T215624
[2024-10-08T21:56:24.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T21:56:24.593+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T21:56:24.595+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
