[2024-10-08T22:08:47.499+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T22:08:47.522+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [queued]>
[2024-10-08T22:08:47.535+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [queued]>
[2024-10-08T22:08:47.535+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 7
[2024-10-08T22:08:47.554+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_extract_container_E3> on 2024-10-08 21:51:57.135226+00:00
[2024-10-08T22:08:47.563+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T22:08:47.565+0000] {standard_task_runner.py:72} INFO - Started process 1383 to run task
[2024-10-08T22:08:47.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_004', 'run_extract_container_E3', 'manual__2024-10-08T21:51:57.135226+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpxyw72l88']
[2024-10-08T22:08:47.566+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask run_extract_container_E3
[2024-10-08T22:08:47.614+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_004.run_extract_container_E3 manual__2024-10-08T21:51:57.135226+00:00 [running]> on host a4706156eccf
[2024-10-08T22:08:47.700+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_004' AIRFLOW_CTX_TASK_ID='run_extract_container_E3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T21:51:57.135226+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T21:51:57.135226+00:00'
[2024-10-08T22:08:47.702+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T22:08:47.728+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-08T22:08:47.732+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-08T22:13:09.988+0000] {docker.py:438} INFO - End of process...
[2024-10-08T22:13:09.988+0000] {docker.py:438} INFO -    Category  ...   Like_First
[2024-10-08T22:13:09.989+0000] {docker.py:438} INFO - 0   Romance  ...   like13,155
[2024-10-08T22:13:09.989+0000] {docker.py:438} INFO - 1   Romance  ...  like140,859
[2024-10-08T22:13:09.989+0000] {docker.py:438} INFO - 2   Romance  ...   like30,213
[2024-10-08T22:13:09.989+0000] {docker.py:438} INFO - 3   Fantasy  ...   like27,535
[2024-10-08T22:13:09.990+0000] {docker.py:438} INFO - 4   Romance  ...   like40,306
[2024-10-08T22:13:09.990+0000] {docker.py:438} INFO - ..      ...  ...          ...
[2024-10-08T22:13:09.990+0000] {docker.py:438} INFO - 68   Horror  ...    like9,598
[2024-10-08T22:13:09.990+0000] {docker.py:438} INFO - 69  Romance  ...   like67,401
[2024-10-08T22:13:09.991+0000] {docker.py:438} INFO - 70    Drama  ...    like4,928
[2024-10-08T22:13:09.991+0000] {docker.py:438} INFO - 71  Fantasy  ...   like88,554
[2024-10-08T22:13:09.991+0000] {docker.py:438} INFO - 72  Fantasy  ...  like136,523
[2024-10-08T22:13:09.991+0000] {docker.py:438} INFO - 
[2024-10-08T22:13:09.992+0000] {docker.py:438} INFO - [73 rows x 9 columns]
[2024-10-08T22:13:10.369+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T22:13:10.370+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_004, task_id=run_extract_container_E3, run_id=manual__2024-10-08T21:51:57.135226+00:00, execution_date=20241008T215157, start_date=20241008T220847, end_date=20241008T221310
[2024-10-08T22:13:10.395+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T22:13:10.420+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T22:13:10.422+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
