[2024-10-08T18:05:30.415+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T18:05:30.432+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_001.run_extract_container_1 manual__2024-10-08T13:47:41.063357+00:00 [queued]>
[2024-10-08T18:05:30.439+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_001.run_extract_container_1 manual__2024-10-08T13:47:41.063357+00:00 [queued]>
[2024-10-08T18:05:30.440+0000] {taskinstance.py:2865} INFO - Starting attempt 6 of 11
[2024-10-08T18:05:30.451+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_extract_container_1> on 2024-10-08 13:47:41.063357+00:00
[2024-10-08T18:05:30.459+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2417) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T18:05:30.461+0000] {standard_task_runner.py:72} INFO - Started process 2418 to run task
[2024-10-08T18:05:30.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_001', 'run_extract_container_1', 'manual__2024-10-08T13:47:41.063357+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp98m2c8o3']
[2024-10-08T18:05:30.462+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask run_extract_container_1
[2024-10-08T18:05:30.504+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_001.run_extract_container_1 manual__2024-10-08T13:47:41.063357+00:00 [running]> on host a4706156eccf
[2024-10-08T18:05:30.576+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_001' AIRFLOW_CTX_TASK_ID='run_extract_container_1' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:47:41.063357+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T13:47:41.063357+00:00'
[2024-10-08T18:05:30.576+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T18:05:30.610+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-08T18:05:30.613+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-08T18:13:47.995+0000] {docker.py:438} INFO - End of process...
[2024-10-08T18:13:47.996+0000] {docker.py:438} INFO -     Category  ...   Like_First
[2024-10-08T18:13:47.996+0000] {docker.py:438} INFO - 0    Romance  ...  like405,350
[2024-10-08T18:13:47.997+0000] {docker.py:438} INFO - 1    Romance  ...   like70,782
[2024-10-08T18:13:47.997+0000] {docker.py:438} INFO - 2      Drama  ...   like20,088
[2024-10-08T18:13:47.997+0000] {docker.py:438} INFO - 3    Romance  ...  like219,948
[2024-10-08T18:13:47.997+0000] {docker.py:438} INFO - 4    Romance  ...  like188,136
[2024-10-08T18:13:47.997+0000] {docker.py:438} INFO - ..       ...  ...          ...
[2024-10-08T18:13:47.998+0000] {docker.py:438} INFO - 145    Drama  ...  like154,081
[2024-10-08T18:13:47.998+0000] {docker.py:438} INFO - 146  Romance  ...   like13,154
[2024-10-08T18:13:47.998+0000] {docker.py:438} INFO - 147  Romance  ...  like140,859
[2024-10-08T18:13:47.998+0000] {docker.py:438} INFO - 148  Romance  ...   like30,213
[2024-10-08T18:13:47.998+0000] {docker.py:438} INFO - 149  Fantasy  ...   like27,534
[2024-10-08T18:13:47.999+0000] {docker.py:438} INFO - 
[2024-10-08T18:13:47.999+0000] {docker.py:438} INFO - [150 rows x 9 columns]
[2024-10-08T18:13:48.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T18:13:48.352+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_001, task_id=run_extract_container_1, run_id=manual__2024-10-08T13:47:41.063357+00:00, execution_date=20241008T134741, start_date=20241008T180530, end_date=20241008T181348
[2024-10-08T18:13:48.399+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T18:13:48.423+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T18:13:48.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
