[2024-10-07T18:23:27.578+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-07T18:23:27.594+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_01.run_extract_container_1 manual__2024-10-07T17:07:25.728941+00:00 [queued]>
[2024-10-07T18:23:27.601+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_01.run_extract_container_1 manual__2024-10-07T17:07:25.728941+00:00 [queued]>
[2024-10-07T18:23:27.601+0000] {taskinstance.py:2865} INFO - Starting attempt 6 of 9
[2024-10-07T18:23:27.614+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_extract_container_1> on 2024-10-07 17:07:25.728941+00:00
[2024-10-07T18:23:27.621+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1475) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T18:23:27.622+0000] {standard_task_runner.py:72} INFO - Started process 1476 to run task
[2024-10-07T18:23:27.622+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_01', 'run_extract_container_1', 'manual__2024-10-07T17:07:25.728941+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpx615tlp7']
[2024-10-07T18:23:27.623+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask run_extract_container_1
[2024-10-07T18:23:27.663+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_01.run_extract_container_1 manual__2024-10-07T17:07:25.728941+00:00 [running]> on host 0e4020a450e4
[2024-10-07T18:23:27.734+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_01' AIRFLOW_CTX_TASK_ID='run_extract_container_1' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T17:07:25.728941+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T17:07:25.728941+00:00'
[2024-10-07T18:23:27.734+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-07T18:23:27.768+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-07T18:23:27.771+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-07T18:44:34.475+0000] {job.py:229} INFO - Heartbeat recovered after 519.66 seconds
