[2024-10-08T13:15:17.527+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T13:15:17.542+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_etl_03.run_extract_container_2 manual__2024-10-08T13:14:03.839465+00:00 [queued]>
[2024-10-08T13:15:17.550+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_etl_03.run_extract_container_2 manual__2024-10-08T13:14:03.839465+00:00 [queued]>
[2024-10-08T13:15:17.550+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-08T13:15:17.561+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_extract_container_2> on 2024-10-08 13:14:03.839465+00:00
[2024-10-08T13:15:17.568+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T13:15:17.569+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2024-10-08T13:15:17.570+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_03', 'run_extract_container_2', 'manual__2024-10-08T13:14:03.839465+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpemcpl1vn']
[2024-10-08T13:15:17.570+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_extract_container_2
[2024-10-08T13:15:17.611+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_etl_03.run_extract_container_2 manual__2024-10-08T13:14:03.839465+00:00 [running]> on host ade6ae45e28b
[2024-10-08T13:15:17.677+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='BB' AIRFLOW_CTX_DAG_ID='dag_etl_03' AIRFLOW_CTX_TASK_ID='run_extract_container_2' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:14:03.839465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T13:14:03.839465+00:00'
[2024-10-08T13:15:17.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T13:15:17.707+0000] {docker.py:367} INFO - Starting docker container from image etl
[2024-10-08T13:15:17.710+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-08T13:15:18.427+0000] {docker.py:438} INFO - Category  ... Like_First
[2024-10-08T13:15:18.427+0000] {docker.py:438} INFO - 0    Romance  ...     405348
[2024-10-08T13:15:18.427+0000] {docker.py:438} INFO - 1    Romance  ...      70779
[2024-10-08T13:15:18.428+0000] {docker.py:438} INFO - 2      Drama  ...      20087
[2024-10-08T13:15:18.428+0000] {docker.py:438} INFO - 3    Romance  ...     219943
[2024-10-08T13:15:18.428+0000] {docker.py:438} INFO - 4    Romance  ...     188133
[2024-10-08T13:15:18.429+0000] {docker.py:438} INFO - 5    Romance  ...     127243
[2024-10-08T13:15:18.429+0000] {docker.py:438} INFO - 6    Romance  ...      46338
[2024-10-08T13:15:18.430+0000] {docker.py:438} INFO - 7    Romance  ...      57171
[2024-10-08T13:15:18.430+0000] {docker.py:438} INFO - 8    Romance  ...     499629
[2024-10-08T13:15:18.430+0000] {docker.py:438} INFO - 9      Drama  ...     127778
[2024-10-08T13:15:18.431+0000] {docker.py:438} INFO - 10   Fantasy  ...     260418
[2024-10-08T13:15:18.431+0000] {docker.py:438} INFO - 11     Drama  ...      73381
[2024-10-08T13:15:18.431+0000] {docker.py:438} INFO - 12   Romance  ...     176035
[2024-10-08T13:15:18.431+0000] {docker.py:438} INFO - 13   Fantasy  ...     161111
[2024-10-08T13:15:18.431+0000] {docker.py:438} INFO - 14   Romance  ...     186938
[2024-10-08T13:15:18.432+0000] {docker.py:438} INFO - 15   Romance  ...      30741
[2024-10-08T13:15:18.432+0000] {docker.py:438} INFO - 16     Drama  ...      43133
[2024-10-08T13:15:18.432+0000] {docker.py:438} INFO - 17   Romance  ...     247670
[2024-10-08T13:15:18.432+0000] {docker.py:438} INFO - 18  Thriller  ...     177955
[2024-10-08T13:15:18.432+0000] {docker.py:438} INFO - 19   Romance  ...     183763
[2024-10-08T13:15:18.433+0000] {docker.py:438} INFO - 
[2024-10-08T13:15:18.433+0000] {docker.py:438} INFO - [20 rows x 9 columns]
[2024-10-08T13:15:18.775+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T13:15:18.776+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_etl_03, task_id=run_extract_container_2, run_id=manual__2024-10-08T13:14:03.839465+00:00, execution_date=20241008T131403, start_date=20241008T131517, end_date=20241008T131518
[2024-10-08T13:15:18.826+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T13:15:18.849+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T13:15:18.850+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
